name: root
dependencies:
  - numpy
  - jupyter
  - scipy
  - matplotlib
  - scikit-learn
  - pip
  - spacy
  - nbconvert
  - pip:
    - https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.3.0-cp36-cp36m-linux_x86_64.whl
    - keras
